model:
  target: models.models.BFRffusion
  base_learning_rate: 1e-5 # lowered from 1e-4 because we are only finetuning
  checkpoint_path: experiments/weights/checkpoint_BFRffusion_FFHQ.ckpt
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "gt"
    control_key: "lq"
    image_size: 64
    channels: 4
    cond_stage_trainable: True
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    sd_locked_steps: 100000  
    CosineAnnealing_steps: 200000

    control_stage_config:
      target: models.transformerBlock.MFEM
      params:
        in_channels: 4
        control_channels: 320
        time_embed_dim: 1280

    unet_config:
      target: models.models.ControlledUnetModel
      params:
        use_checkpoint: True
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: models.prompt.TTPM
      params:
        model_channels: 320
        dropout: 0.0
        time_embed_dim: 1280
        prompt_channels: 77
        prompt_dim: 1024
        hidden_size: 512
        num_heads: 8

# -------------------------------------------------
#  DATA
# -------------------------------------------------
data:
  target: data.dataset_instantiate.DataModuleFromConfig
  params:
    batch_size: 1 # size=6: 20gb VRAM, size=20: 25gb VRAM, size=30: 27.5gb VRAM
    num_workers: 4
    wrap: false

    # ---------- TRAIN ----------
    train:
      target: data.paired_image_dataset.PairedImageDataset
      params:
        phase: train
        dataroot_gt: /gscratch/krishna/vilin/BFRffusion/data/images512x512/train_pico/gt
        dataroot_lq: /gscratch/krishna/vilin/BFRffusion/data/images512x512/train_pico/lq
        io_backend:
          type: disk
        gt_size: -1      # random crops
        use_hflip: false
        use_rot: false
        scale: 1
        mean: [0.5, 0.5, 0.5]
        std:  [0.5, 0.5, 0.5]

# -------------------------------------------------
#  PYTORCH-LIGHTNING
# -------------------------------------------------
lightning:
  use_tb: True

  modelcheckpoint:
    verbose: True
    every_n_train_steps: 1
    save_last: True
    save_weights_only: False

  use_image_logger: True
  image_logger:
    batch_frequency: 10
    max_images: 1
    clamp: True

  use_val: True
  val:
    val_freq: 10
    save_img: true
    metrics:
      psnr_ssim: false
      lpips: false

    dataset:
      num_workers: 4
      batch_size: 1
      target: data.paired_image_dataset.PairedImageDataset
      params:
        phase: test
        dataroot_gt: /gscratch/krishna/vilin/BFRffusion/data/images512x512/train_pico/gt
        dataroot_lq: /gscratch/krishna/vilin/BFRffusion/data/images512x512/train_pico/lq
        io_backend:
          type: disk
        scale: 1
        mean: [0.5, 0.5, 0.5]
        std:  [0.5, 0.5, 0.5]

  trainer:
    # precision: 16
    benchmark: True
    max_steps: 200 # lowered from 250_000 because we are only finetuning
    gpus: 1
